//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int Order_ID { get; set; }
        public string Order_NAME { get; set; }
        public int Order_MANAGER { get; set; }
        public int Order_DESTINATION { get; set; }
        public int Order_DURATION { get; set; }
        public int Order_PRICE { get; set; }
        public int Order_CLIENT { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual MANAGER MANAGER { get; set; }
    }
}
